# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Neil Spurgeon - Design & Development
email: neilspurgeon@gmail.com
description: Designer and front end web developer with a focus on user interface design, user experience design, front end web development, and user interface development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://neilspurgeon.com" # the base hostname & protocol for your site
github_username:  neilspurgeon

# Build settings
markdown: kramdown
sass:
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-responsive-image
  - jekyll-autoprefixer

collections:
  projects:
    output: true
    permalink: "/:permalink"
  pages:
    output: true

exclude:
  - node_modules
  - webpack
  - vendor/bundle

responsive_image:
  template: _includes/responsive-image.html
  default_quality: 100
  sizes:
    - width: 480
      quality: 80
    - width: 800
      quality: 80
    - width: 1440
    - width: 2800
  output_path_format: assets/images/resized/%{width}/%{basename}
  cache: false

media_renditions:
  tile_2col:
    sizes:
      - "(min-width: 1801px) 1440px"
      - "(max-width: 1800px) and (min-width: 961px) 800px"
      - "(max-width: 960px) and (min-width: 768px) 480px"
      - "(max-width: 767px) and (min-width: 480px) 800px"
      - "(max-width: 479px) 480px"
