# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Neil Spurgeon - Design & Development
email: neilspurgeon@gmail.com
description: Designer and front end web developer with a ocus on user interface design, user experience design, front end web development, and user interface development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://neilspurgeon.com" # the base hostname & protocol for your site
github_username:  neilspurgeon

# Build settings
markdown: kramdown
sass:
  style: compressed


collections:
  projects:
    output: true
    permalink: "/:permalink"